version: '3'
services:
  vue:
    build:
      context: .
    #      dockerfile: Dockerfile
    #    tty: true
    image: node:lts
    working_dir: /usr/src/app
    volumes:
      - ./vue:/usr/src/app
    command: npm run dev
    ports:
      - "5173:5173"
    restart: always
