version: '3'
services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    #    tty: true
    volumes:
      - ./vue:/usr/src/app
    command: npm run dev
    ports:
      - "5173:5173"
